apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: production
data:
  db-user: cHJvZC11c2Vy # base64 encoded value
  db-password: cHJvZC1wYXNzd29yZA== # base64 encoded value
type: Opaque

