apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-prod
  namespace: production
  labels:
    app: my-app
    environment: production
data:
  APP_NAME: "Production App"
  LOG_LEVEL: "error"
  DATABASE_URL: "postgres://prod-user:prod-password@prod-db-host:5432/prod-dbname"

