apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  labels:
    app: my-app
    environment: production
data:
  # Configuration values as key-value pairs
  APP_NAME: "My Awesome App"
  LOG_LEVEL: "info"
  DATABASE_URL: "postgres://user:password@hostname:5432/dbname"

